<?xml version="1.0" ?>
<!-- SPDX-License-Identifier: BSD-3-Clause -->
<!-- SPDX-FileCopyrightText: Czech Technical University in Prague -->
<package format="3">
  <name>robot_body_filter</name>
  <version>1.3.2</version>

  <description>Filters the robot's body out of laser scans or point clouds.</description>

  <license file="LICENSE">BSD</license>

  <url type="repository">https://github.com/ctu-vras/robot_body_filter</url>
  <url type="bugtracker">https://github.com/ctu-vras/robot_body_filter/issues</url>
  <url type="website">https://index.ros.org/p/robot_body_filter</url>

  <author>Eitan Marder-Eppstein</author>
  <author>Tomas Petricek</author>
  <author>Martin Pecka</author>
  <author>Sebastian Pelletier</author>
  <author>David V. Lu!!</author>

  <maintainer email="peckama2@fel.cvut.cz">Martin Pecka</maintainer>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>filters</depend>
  <depend>geometric_shapes</depend>
  <depend>geometry_msgs</depend>
  <depend>laser_geometry</depend>
  <depend>libpcl-all-dev</depend>
  <depend>moveit_core</depend>
  <depend>moveit_ros_perception</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>urdf</depend>
  <depend>visualization_msgs</depend>

  <build_depend>cras_cpp_common</build_depend>
  <exec_depend>cras_cpp_common</exec_depend>

  <build_depend>libfcl-dev</build_depend>
  <exec_depend>libfcl</exec_depend>

  <build_depend>pcl_conversions</build_depend>
  <exec_depend>pcl_conversions</exec_depend>

  <build_depend>pkg-config</build_depend>
  <build_depend>tf2_eigen</build_depend>
  <build_depend>tf2_sensor_msgs</build_depend>
  <build_depend>rosidl_default_generators</build_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>cras_lint</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>ros_testing</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
