# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Czech Technical University in Prague

# This is an example filter config for tracked vehicle Absolem from Czech Technical University's
# VRAS team. The robot is equipped with a 2D lidar attached to a rotating pivot point.

# This config is meant to be loaded by laser_filters/scan_to_scan_filter_chain .
# See vlp16_params.yaml for an example how to load the filter into sensor_filters/pointcloud2_filter_chain .

laser_filter:
 ros__parameters:
  filter1:
    name: RobotBodyFilter
    type: robot_body_filter/RobotBodyFilterLaserScan
    params:
      frames:
        fixed: 'odom'
        sensor: 'laser'
      filter:
        model_pose_update_interval: 0.002  # do not get lower, the processing is then too slow
      sensor:
        point_by_point: True
        min_distance: 0.03
        max_distance: 10.0
      ignored_links:
        bounding_sphere: ["antenna", "base_link::big_collision_box"]
        shadow_test: ["laser", "base_link::big_collision_box"]
      body_model:
        inflation:
          scale: 1.07
          padding: 0.01
        robot_description_topic: 'robot_description'
      transforms:
        buffer_length: 60.0
        timeout:
          reachable: 0.2
          unreachable: 0.2
      bounding_sphere:
        compute: True
        debug: True
        marker: True
        publish_cut_out_pointcloud: True
      bounding_box:
        compute: True
        debug: True
        marker: True
        publish_cut_out_pointcloud: True
      oriented_bounding_box:
        compute: True
        debug: True
        marker: True
        publish_cut_out_pointcloud: True
      local_bounding_box:
        frame_id: "base_link"
        compute: True
        debug: True
        marker: True
        publish_cut_out_pointcloud: True
      debug:
        pcl:
          inside: True
          clip: True
          shadow: True
        marker:
          contains: True
          shadow: True
